modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0-only"

[[mixins]]
config="embeddium.mixins.json"

[[mods]]
modId="beddium"
version="${version}"
displayName="Beddium"
logoFile="icon.png"
description='''
(Un)Official fork of Embeddium for Forge
'''
credits="embeddedt, NanoLive, CaffeineMC"
authors="Ven"

[[mods]]
modId = "rubidium"
version = "0.7.1"
displayName = "Rubidium (Beddium)"
description = '''
Stub, to allow mods detecting Rubidium to function as expected.
'''

[[mods]]
modId = "embeddium"
version = "1.0.5"
displayName = "Embeddium (Beddium)"
description = '''
Stub, to allow mods detecting Embeddium to function as expected.
'''

# Enforce new enough Oculus
[[dependencies.beddium]]
modId = "oculus"
type = "optional"
mandatory = false
versionRange = "(1.6.15,)"
ordering = "BEFORE"
side = "CLIENT"
